dynamixels:
  port_info:
    port_name: /dev/ttyUSB0
    baudrate: 3000000
    protocol_version: 2
  control_mode: position
  read_values:
    read_position: true
  device_info:
    gripper_roll_joint:
      id: 0
      model_number: 1030
    gripper_finger_servo_joint:
      id: 1
      model_number: 1020
      mounting_offset: -1.5

  
      
  
