dynamixels:
  port_info:
    port_name: /dev/rs485_extern
    baudrate: 3000000
    protocol_version: 2
  device_info:
    gripper_roll_joint:
      id: 0
      model_number: 1030
    gripper_finger_servo_joint:
      id: 1
      model_number: 1020

  
      
  